#! /bin/bash
### backup .../Dropbox/{ODPRTO,SKUPNI} from doma to $HOME/majstaf/bckps_all/drpbx_bckp
###

# timestamp
function tms() {
    echo -n "[ $(date +%Y%m%d_%H%M%S) ] "
}

crtn=100
function crtc() {
    for ((i=1; i<=$1; i++)); do
        echo -n "-"
    done
    echo
}


# MAIN

tms; echo "Started: $0"
tms; crtc 3
gDejtt="$(date +%Y%m%d_%H%M)"
gDbx=$HOME/OLDHDD/Dropbox
gDbo=${gDbx}/ODPRTO
gDbs=${gDbx}/SKUPNI
gDest=$HOME/majstaf/bckps_all/bckp_drpbx
gLog=$HOME/majstaf/bckps_all/bckp.log

tms; echo "Removing old files from ${gDest} ... "
rm -v ${gDest}/* | grep -v '^[[:space:]]*$' | while read line; do (tms; echo $line); done
tms; echo "[OK]"

tms; echo "Backing up ... /Dropbox/{SKUPNI,ODPRTO}/*"
tms; echo -n "to $HOME/majstaf/bckps_all/drpbx_bckp  "

tar -c --checkpoint=200 --checkpoint-action=dot -zf ${gDest}/rut@home@rgregor@bckps_all@drpbx_bckp@dropbox@skupni_${gDejtt}.tar.gz -C ${gDbx} SKUPNI
echo
tar -c --checkpoint=200 --checkpoint-action=dot -zf ${gDest}/rut@home@rgregor@bckps_all@drpbx_bckp@dropbox@odprto_${gDejtt}.tar.gz -c ${gDbx} ODPRTO

echo
(tms; echo "Successfully backed up .../Dropbox/{ODPRTO,SKUPNO} to ${gDest}/") | tee -a ${gLog} # append to log
tms; echo "DONE!"
crtc 3
